import type { Metadata } from "next";

import {Roboto, Montserrat} from 'next/font/google';
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });
const montserrat = Montserrat({ subsets: ["latin"], weight: ["600", "700"] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.className} bg-background text-dark antialiased`}
    >
      <body
        className="min-h-screen font-sans"
      >
        {children}
      </body>
    </html>
  );
}
